import type { Metadata } from "next";
import "./globals.css";
import {
  Menu,
  X,
  Smartphone,
  Facebook,
  Instagram,
  Linkedin,
  ChevronRight,
} from "lucide-react";
import Link from "next/link";
import { APP_LINKS, COMPANY_INFO, NAV_ITEMS } from "../constants/constants";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex flex-col min-h-screen font-sans bg-dark-100 text-dark-900 relative">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
